import os

from django.db.models import FilePathField
from django.test import SimpleTestCase


class FilePathFieldTests(SimpleTestCase):
    def test_path(self):
        """
        Tests that the path of a FilePathField is correctly set and retrieved.

        Verifies that the path provided to the FilePathField is stored as an instance
        attribute and that it is also correctly set on the form field generated by the
        FilePathField. Ensures that the path remains consistent across the FilePathField
        instance and its associated form field.
        """
        path = os.path.dirname(__file__)
        field = FilePathField(path=path)
        self.assertEqual(field.path, path)
        self.assertEqual(field.formfield().path, path)

    def test_callable_path(self):
        path = os.path.dirname(__file__)

        def generate_path():
            return path

        field = FilePathField(path=generate_path)
        self.assertEqual(field.path(), path)
        self.assertEqual(field.formfield().path, path)
