from django.db.models.functions import Random
from django.test import TestCase

from ..models import FloatModel


class RandomTests(TestCase):
    def test(self):
        """
        Tests that the Random database function returns a float value between 0 and 1.

        This test case verifies that the random value generated by the database function
        is an instance of a float, and that its value falls within the expected range of 0 (inclusive) and 1 (exclusive).
        """
        FloatModel.objects.create()
        obj = FloatModel.objects.annotate(random=Random()).first()
        self.assertIsInstance(obj.random, float)
        self.assertGreaterEqual(obj.random, 0)
        self.assertLess(obj.random, 1)
