from django.test import SimpleTestCase

from ..utils import setup

multiline_string = """
Hello,
boys.
How
are
you
gentlemen.
"""


class MultilineTests(SimpleTestCase):
    @setup({"multiline01": multiline_string})
    def test_multiline01(self):
        """
        .Tests rendering of a multiline string.

        This test case verifies that the rendering engine correctly handles multiline strings.
        It checks if the output generated by the engine matches the expected multiline string.
        The test ensures that the rendering process preserves the original string's formatting and content.
        """
        output = self.engine.render_to_string("multiline01")
        self.assertEqual(output, multiline_string)
